
target 'DWT' do

  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'
  # Pods for DWT

  platform :ios, '9.0'
  require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
  
 
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'
  
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'



  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Unomment this line if you want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS

  pod 'GoogleSignIn', '~> 5.0.2'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
 
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  # pod 'FBAudienceNetwork', '~> 5.1.0' #facebook ads

  pod 'Google-Mobile-Ads-SDK'
  
   pod 'GoogleIDFASupport', '~> 3.14.0'
    
    
    pod 'Firebase/Core'

    pod 'Firebase/Messaging'
    pod 'FirebaseAnalytics'

    
    
    # Facebook FBSDK
    pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

   
  
   
    pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
    pod 'GooglePlaces'
    pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS

    pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'
    
    pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

    pod 'RNIap', :path => '../node_modules/react-native-iap'

    pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

    pod 'react-native-admob', :path => '../node_modules/react-native-admob'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


    pod 'react-native-simple-toast', :path => '../node_modules/react-native-simple-toast'
    pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

    pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'

    pod 'RCTRestart', :path => '../node_modules/react-native-restart/ios'

    pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
    pod 'lottie-ios', :path => '../node_modules/lottie-ios'


    pod 'Firebase/Auth','~> 6.17.0'
    # pod 'Firebase/Auth'
    pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

    
    pod 'RNAppleAuthentication', :path => '../node_modules/@invertase/react-native-apple-authentication'

    pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  end

  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-google-maps'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
        end
      end
      if target.name == "React"
        target.remove_from_project
      end
    end
  end


